#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

insmod test.ko
chmod 777 /dev/test
echo 0 > /proc/sys/kernel/kptr_restrict

setsid cttyhack setuidgid 0 sh

umount /proc
umount /sys
poweroff -d 0  -f
